### ISSUE TITLE
Enable install event manager gateway

### ISSUE THREAD

**Issue by gyliu513** [cloud-pak-gitops/cp4waiops-gitops#23]
@liyanwei93

**Comment by gyliu513** [comment]
We should be able to turn on and turn off AI Manager, EventManagerGateway using values.yaml.

```yaml
spec:
  ai-manager:
    enabled: false
  event-manager-gateway:
    enabled: false
```
